/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStats {
  'waterIntakeMl' : bigint,
  'date' : string,
  'stepsCount' : bigint,
}
export interface DietRecommendation {
  'dailyCaloriesRequired' : bigint,
  'createdAt' : Time,
  'dietType' : DietType,
  'planJson' : string,
}
export type DietType = { 'veg' : null } |
  { 'nonVeg' : null };
export type DifficultyLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface Exercise {
  'id' : bigint,
  'difficultyLevel' : DifficultyLevel,
  'restSeconds' : bigint,
  'setsRecommended' : bigint,
  'name' : string,
  'description' : string,
  'repsRecommended' : bigint,
  'imageUrl' : [] | [ExternalBlob],
  'category' : WorkoutCategory,
}
export type ExternalBlob = Uint8Array;
export type FitnessGoal = { 'weightLoss' : null } |
  { 'muscleGain' : null } |
  { 'maintainFitness' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Notification {
  'id' : bigint,
  'createdAt' : Time,
  'message' : string,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : bigint,
  'name' : string,
  'weightKg' : number,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry {
  'id' : bigint,
  'date' : string,
  'weightKg' : number,
}
export type WorkoutCategory = { 'abs' : null } |
  { 'custom' : null } |
  { 'back' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'cardio' : null };
export interface WorkoutLog {
  'id' : bigint,
  'date' : string,
  'durationMinutes' : bigint,
  'exerciseName' : string,
  'category' : WorkoutCategory,
  'caloriesBurned' : bigint,
}
export interface WorkoutPlan {
  'difficultyLevel' : DifficultyLevel,
  'goal' : FitnessGoal,
  'createdAt' : Time,
  'planJson' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCallerWeightEntry' : ActorMethod<[number, string], undefined>,
  'addOrUpdateCallerDailyStats' : ActorMethod<
    [string, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExercise' : ActorMethod<
    [
      WorkoutCategory,
      string,
      string,
      bigint,
      bigint,
      bigint,
      DifficultyLevel,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'createNotification' : ActorMethod<[string], undefined>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'deleteWorkoutLog' : ActorMethod<[bigint], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerDailyStats' : ActorMethod<[string], DailyStats>,
  'getCallerDietRecommendation' : ActorMethod<[], DietRecommendation>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWeightEntries' : ActorMethod<[], Array<WeightEntry>>,
  'getCallerWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getCallerWorkoutPlan' : ActorMethod<[], WorkoutPlan>,
  'getExercisesByCategory' : ActorMethod<[WorkoutCategory], Array<Exercise>>,
  'getLatestNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkout' : ActorMethod<
    [WorkoutCategory, string, bigint, bigint, string],
    undefined
  >,
  'saveCallerDietRecommendation' : ActorMethod<
    [DietType, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCallerWorkoutPlan' : ActorMethod<
    [FitnessGoal, DifficultyLevel, string],
    undefined
  >,
  'updateExercise' : ActorMethod<[Exercise], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];