/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkoutCategory = IDL.Variant({
  'abs' : IDL.Null,
  'custom' : IDL.Null,
  'back' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'cardio' : IDL.Null,
});
export const DifficultyLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FitnessGoal = IDL.Variant({
  'weightLoss' : IDL.Null,
  'muscleGain' : IDL.Null,
  'maintainFitness' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'fitnessGoal' : FitnessGoal,
  'heightCm' : IDL.Nat,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
});
export const DailyStats = IDL.Record({
  'waterIntakeMl' : IDL.Nat,
  'date' : IDL.Text,
  'stepsCount' : IDL.Nat,
});
export const Time = IDL.Int;
export const DietType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
export const DietRecommendation = IDL.Record({
  'dailyCaloriesRequired' : IDL.Nat,
  'createdAt' : Time,
  'dietType' : DietType,
  'planJson' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const WorkoutLog = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'exerciseName' : IDL.Text,
  'category' : WorkoutCategory,
  'caloriesBurned' : IDL.Nat,
});
export const WorkoutPlan = IDL.Record({
  'difficultyLevel' : DifficultyLevel,
  'goal' : FitnessGoal,
  'createdAt' : Time,
  'planJson' : IDL.Text,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : DifficultyLevel,
  'restSeconds' : IDL.Nat,
  'setsRecommended' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'repsRecommended' : IDL.Nat,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'category' : WorkoutCategory,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCallerWeightEntry' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'addOrUpdateCallerDailyStats' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExercise' : IDL.Func(
      [
        WorkoutCategory,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        DifficultyLevel,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'createNotification' : IDL.Func([IDL.Text], [], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'deleteWorkoutLog' : IDL.Func([IDL.Nat], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerDailyStats' : IDL.Func([IDL.Text], [DailyStats], ['query']),
  'getCallerDietRecommendation' : IDL.Func([], [DietRecommendation], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getCallerWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getCallerWorkoutPlan' : IDL.Func([], [WorkoutPlan], ['query']),
  'getExercisesByCategory' : IDL.Func(
      [WorkoutCategory],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getLatestNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkout' : IDL.Func(
      [WorkoutCategory, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerDietRecommendation' : IDL.Func(
      [DietType, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCallerWorkoutPlan' : IDL.Func(
      [FitnessGoal, DifficultyLevel, IDL.Text],
      [],
      [],
    ),
  'updateExercise' : IDL.Func([Exercise], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkoutCategory = IDL.Variant({
    'abs' : IDL.Null,
    'custom' : IDL.Null,
    'back' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const DifficultyLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FitnessGoal = IDL.Variant({
    'weightLoss' : IDL.Null,
    'muscleGain' : IDL.Null,
    'maintainFitness' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'fitnessGoal' : FitnessGoal,
    'heightCm' : IDL.Nat,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
  });
  const DailyStats = IDL.Record({
    'waterIntakeMl' : IDL.Nat,
    'date' : IDL.Text,
    'stepsCount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const DietType = IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null });
  const DietRecommendation = IDL.Record({
    'dailyCaloriesRequired' : IDL.Nat,
    'createdAt' : Time,
    'dietType' : DietType,
    'planJson' : IDL.Text,
  });
  const WeightEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const WorkoutLog = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'exerciseName' : IDL.Text,
    'category' : WorkoutCategory,
    'caloriesBurned' : IDL.Nat,
  });
  const WorkoutPlan = IDL.Record({
    'difficultyLevel' : DifficultyLevel,
    'goal' : FitnessGoal,
    'createdAt' : Time,
    'planJson' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : DifficultyLevel,
    'restSeconds' : IDL.Nat,
    'setsRecommended' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'repsRecommended' : IDL.Nat,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'category' : WorkoutCategory,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCallerWeightEntry' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'addOrUpdateCallerDailyStats' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExercise' : IDL.Func(
        [
          WorkoutCategory,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          DifficultyLevel,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'createNotification' : IDL.Func([IDL.Text], [], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'deleteWorkoutLog' : IDL.Func([IDL.Nat], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerDailyStats' : IDL.Func([IDL.Text], [DailyStats], ['query']),
    'getCallerDietRecommendation' : IDL.Func(
        [],
        [DietRecommendation],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getCallerWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getCallerWorkoutPlan' : IDL.Func([], [WorkoutPlan], ['query']),
    'getExercisesByCategory' : IDL.Func(
        [WorkoutCategory],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getLatestNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkout' : IDL.Func(
        [WorkoutCategory, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerDietRecommendation' : IDL.Func(
        [DietType, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCallerWorkoutPlan' : IDL.Func(
        [FitnessGoal, DifficultyLevel, IDL.Text],
        [],
        [],
      ),
    'updateExercise' : IDL.Func([Exercise], [], []),
  });
};

export const init = ({ IDL }) => { return []; };