/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    restSeconds: bigint;
    setsRecommended: bigint;
    name: string;
    description: string;
    repsRecommended: bigint;
    imageUrl?: ExternalBlob;
    category: WorkoutCategory;
}
export interface DietRecommendation {
    dailyCaloriesRequired: bigint;
    createdAt: Time;
    dietType: DietType;
    planJson: string;
}
export interface WorkoutLog {
    id: bigint;
    date: string;
    durationMinutes: bigint;
    exerciseName: string;
    category: WorkoutCategory;
    caloriesBurned: bigint;
}
export type Time = bigint;
export interface DailyStats {
    waterIntakeMl: bigint;
    date: string;
    stepsCount: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WorkoutPlan {
    difficultyLevel: DifficultyLevel;
    goal: FitnessGoal;
    createdAt: Time;
    planJson: string;
}
export interface Notification {
    id: bigint;
    createdAt: Time;
    message: string;
}
export interface WeightEntry {
    id: bigint;
    date: string;
    weightKg: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    age: bigint;
    fitnessGoal: FitnessGoal;
    heightCm: bigint;
    name: string;
    weightKg: number;
    gender: Gender;
}
export enum DietType {
    veg = "veg",
    nonVeg = "nonVeg"
}
export enum DifficultyLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum FitnessGoal {
    weightLoss = "weightLoss",
    muscleGain = "muscleGain",
    maintainFitness = "maintainFitness"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkoutCategory {
    abs = "abs",
    custom = "custom",
    back = "back",
    chest = "chest",
    legs = "legs",
    cardio = "cardio"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCallerWeightEntry(weightKg: number, date: string): Promise<void>;
    addOrUpdateCallerDailyStats(date: string, steps: bigint, water: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createExercise(category: WorkoutCategory, name: string, description: string, setsRec: bigint, repsRec: bigint, restSecs: bigint, difficulty: DifficultyLevel, imageUrl: ExternalBlob | null): Promise<void>;
    createNotification(message: string): Promise<void>;
    deleteExercise(exerciseId: bigint): Promise<void>;
    deleteWorkoutLog(logId: bigint): Promise<void>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerDailyStats(date: string): Promise<DailyStats>;
    getCallerDietRecommendation(): Promise<DietRecommendation>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWeightEntries(): Promise<Array<WeightEntry>>;
    getCallerWorkoutLogs(): Promise<Array<WorkoutLog>>;
    getCallerWorkoutPlan(): Promise<WorkoutPlan>;
    getExercisesByCategory(category: WorkoutCategory): Promise<Array<Exercise>>;
    getLatestNotifications(): Promise<Array<Notification>>;
    getUserCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    logWorkout(category: WorkoutCategory, exercise: string, duration: bigint, calories: bigint, date: string): Promise<void>;
    saveCallerDietRecommendation(dietType: DietType, dailyCalories: bigint, planJson: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCallerWorkoutPlan(goal: FitnessGoal, difficulty: DifficultyLevel, planJson: string): Promise<void>;
    updateExercise(exercise: Exercise): Promise<void>;
}
import type { DietRecommendation as _DietRecommendation, DietType as _DietType, DifficultyLevel as _DifficultyLevel, Exercise as _Exercise, ExternalBlob as _ExternalBlob, FitnessGoal as _FitnessGoal, Gender as _Gender, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutCategory as _WorkoutCategory, WorkoutLog as _WorkoutLog, WorkoutPlan as _WorkoutPlan, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCallerWeightEntry(arg0: number, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallerWeightEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallerWeightEntry(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateCallerDailyStats(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCallerDailyStats(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCallerDailyStats(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createExercise(arg0: WorkoutCategory, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: DifficultyLevel, arg7: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createExercise(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n12(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExercise(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n12(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createNotification(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async deleteWorkoutLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutLog(arg0);
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerDailyStats(arg0: string): Promise<DailyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDailyStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDailyStats(arg0);
            return result;
        }
    }
    async getCallerDietRecommendation(): Promise<DietRecommendation> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDietRecommendation();
                return from_candid_DietRecommendation_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDietRecommendation();
            return from_candid_DietRecommendation_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWeightEntries(): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWeightEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWeightEntries();
            return result;
        }
    }
    async getCallerWorkoutLogs(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWorkoutLogs();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWorkoutLogs();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWorkoutPlan(): Promise<WorkoutPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWorkoutPlan();
                return from_candid_WorkoutPlan_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWorkoutPlan();
            return from_candid_WorkoutPlan_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercisesByCategory(arg0: WorkoutCategory): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByCategory(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByCategory(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNotifications();
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logWorkout(arg0: WorkoutCategory, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(to_candid_WorkoutCategory_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerDietRecommendation(arg0: DietType, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerDietRecommendation(to_candid_DietType_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerDietRecommendation(to_candid_DietType_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerWorkoutPlan(arg0: FitnessGoal, arg1: DifficultyLevel, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerWorkoutPlan(to_candid_FitnessGoal_n48(this._uploadFile, this._downloadFile, arg0), to_candid_DifficultyLevel_n12(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerWorkoutPlan(to_candid_FitnessGoal_n48(this._uploadFile, this._downloadFile, arg0), to_candid_DifficultyLevel_n12(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateExercise(arg0: Exercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(await to_candid_Exercise_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(await to_candid_Exercise_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DietRecommendation_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietRecommendation): DietRecommendation {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DietType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietType): DietType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Exercise_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Promise<Exercise> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FitnessGoal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutCategory): WorkoutCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutLog_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutLog): WorkoutLog {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutPlan_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutPlan): WorkoutPlan {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessGoal: _FitnessGoal;
    heightCm: bigint;
    name: string;
    weightKg: number;
    gender: _Gender;
}): {
    age: bigint;
    fitnessGoal: FitnessGoal;
    heightCm: bigint;
    name: string;
    weightKg: number;
    gender: Gender;
} {
    return {
        age: value.age,
        fitnessGoal: from_candid_FitnessGoal_n20(_uploadFile, _downloadFile, value.fitnessGoal),
        heightCm: value.heightCm,
        name: value.name,
        weightKg: value.weightKg,
        gender: from_candid_Gender_n22(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyCaloriesRequired: bigint;
    createdAt: _Time;
    dietType: _DietType;
    planJson: string;
}): {
    dailyCaloriesRequired: bigint;
    createdAt: Time;
    dietType: DietType;
    planJson: string;
} {
    return {
        dailyCaloriesRequired: value.dailyCaloriesRequired,
        createdAt: value.createdAt,
        dietType: from_candid_DietType_n26(_uploadFile, _downloadFile, value.dietType),
        planJson: value.planJson
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    durationMinutes: bigint;
    exerciseName: string;
    category: _WorkoutCategory;
    caloriesBurned: bigint;
}): {
    id: bigint;
    date: string;
    durationMinutes: bigint;
    exerciseName: string;
    category: WorkoutCategory;
    caloriesBurned: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        durationMinutes: value.durationMinutes,
        exerciseName: value.exerciseName,
        category: from_candid_WorkoutCategory_n33(_uploadFile, _downloadFile, value.category),
        caloriesBurned: value.caloriesBurned
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    difficultyLevel: _DifficultyLevel;
    goal: _FitnessGoal;
    createdAt: _Time;
    planJson: string;
}): {
    difficultyLevel: DifficultyLevel;
    goal: FitnessGoal;
    createdAt: Time;
    planJson: string;
} {
    return {
        difficultyLevel: from_candid_DifficultyLevel_n37(_uploadFile, _downloadFile, value.difficultyLevel),
        goal: from_candid_FitnessGoal_n20(_uploadFile, _downloadFile, value.goal),
        createdAt: value.createdAt,
        planJson: value.planJson
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: _DifficultyLevel;
    restSeconds: bigint;
    setsRecommended: bigint;
    name: string;
    description: string;
    repsRecommended: bigint;
    imageUrl: [] | [_ExternalBlob];
    category: _WorkoutCategory;
}): Promise<{
    id: bigint;
    difficultyLevel: DifficultyLevel;
    restSeconds: bigint;
    setsRecommended: bigint;
    name: string;
    description: string;
    repsRecommended: bigint;
    imageUrl?: ExternalBlob;
    category: WorkoutCategory;
}> {
    return {
        id: value.id,
        difficultyLevel: from_candid_DifficultyLevel_n37(_uploadFile, _downloadFile, value.difficultyLevel),
        restSeconds: value.restSeconds,
        setsRecommended: value.setsRecommended,
        name: value.name,
        description: value.description,
        repsRecommended: value.repsRecommended,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n42(_uploadFile, _downloadFile, value.imageUrl)),
        category: from_candid_WorkoutCategory_n33(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintainFitness: null;
}): FitnessGoal {
    return "weightLoss" in value ? FitnessGoal.weightLoss : "muscleGain" in value ? FitnessGoal.muscleGain : "maintainFitness" in value ? FitnessGoal.maintainFitness : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    nonVeg: null;
}): DietType {
    return "veg" in value ? DietType.veg : "nonVeg" in value ? DietType.nonVeg : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    abs: null;
} | {
    custom: null;
} | {
    back: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
}): WorkoutCategory {
    return "abs" in value ? WorkoutCategory.abs : "custom" in value ? WorkoutCategory.custom : "back" in value ? WorkoutCategory.back : "chest" in value ? WorkoutCategory.chest : "legs" in value ? WorkoutCategory.legs : "cardio" in value ? WorkoutCategory.cardio : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): DifficultyLevel {
    return "intermediate" in value ? DifficultyLevel.intermediate : "beginner" in value ? DifficultyLevel.beginner : "advanced" in value ? DifficultyLevel.advanced : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutLog>): Array<WorkoutLog> {
    return value.map((x)=>from_candid_WorkoutLog_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Promise<Array<Exercise>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Exercise_n40(_uploadFile, _downloadFile, x)));
}
function to_candid_DietType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): _DietType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_DifficultyLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Exercise_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): Promise<_Exercise> {
    return await to_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FitnessGoal_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutCategory): _WorkoutCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    fitnessGoal: FitnessGoal;
    heightCm: bigint;
    name: string;
    weightKg: number;
    gender: Gender;
}): {
    age: bigint;
    fitnessGoal: _FitnessGoal;
    heightCm: bigint;
    name: string;
    weightKg: number;
    gender: _Gender;
} {
    return {
        age: value.age,
        fitnessGoal: to_candid_FitnessGoal_n48(_uploadFile, _downloadFile, value.fitnessGoal),
        heightCm: value.heightCm,
        name: value.name,
        weightKg: value.weightKg,
        gender: to_candid_Gender_n50(_uploadFile, _downloadFile, value.gender)
    };
}
async function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    restSeconds: bigint;
    setsRecommended: bigint;
    name: string;
    description: string;
    repsRecommended: bigint;
    imageUrl?: ExternalBlob;
    category: WorkoutCategory;
}): Promise<{
    id: bigint;
    difficultyLevel: _DifficultyLevel;
    restSeconds: bigint;
    setsRecommended: bigint;
    name: string;
    description: string;
    repsRecommended: bigint;
    imageUrl: [] | [_ExternalBlob];
    category: _WorkoutCategory;
}> {
    return {
        id: value.id,
        difficultyLevel: to_candid_DifficultyLevel_n12(_uploadFile, _downloadFile, value.difficultyLevel),
        restSeconds: value.restSeconds,
        setsRecommended: value.setsRecommended,
        name: value.name,
        description: value.description,
        repsRecommended: value.repsRecommended,
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageUrl)) : candid_none(),
        category: to_candid_WorkoutCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutCategory): {
    abs: null;
} | {
    custom: null;
} | {
    back: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    cardio: null;
} {
    return value == WorkoutCategory.abs ? {
        abs: null
    } : value == WorkoutCategory.custom ? {
        custom: null
    } : value == WorkoutCategory.back ? {
        back: null
    } : value == WorkoutCategory.chest ? {
        chest: null
    } : value == WorkoutCategory.legs ? {
        legs: null
    } : value == WorkoutCategory.cardio ? {
        cardio: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == DifficultyLevel.intermediate ? {
        intermediate: null
    } : value == DifficultyLevel.beginner ? {
        beginner: null
    } : value == DifficultyLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietType): {
    veg: null;
} | {
    nonVeg: null;
} {
    return value == DietType.veg ? {
        veg: null
    } : value == DietType.nonVeg ? {
        nonVeg: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    weightLoss: null;
} | {
    muscleGain: null;
} | {
    maintainFitness: null;
} {
    return value == FitnessGoal.weightLoss ? {
        weightLoss: null
    } : value == FitnessGoal.muscleGain ? {
        muscleGain: null
    } : value == FitnessGoal.maintainFitness ? {
        maintainFitness: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
